# This is a basic workflow to help you get started with Actions

name: Release zip

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install zip
      - name: Zip files
        run: pwd && cd .. && mkdir data && mv my-soundboard-sounds/* data/ && zip -r sounds.zip data && cd my-soundboard-sounds && mv ../sounds.zip ./
      - name: Add version file
        run: git rev-parse --short HEAD > version.txt
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: true
          files: |
            version.txt
            sounds.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
